require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/fixtures/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Rspec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/*.rb'
    - 'spec/requests/**/*.rb'
