---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/tipsters":
    get:
      summary: List all Tipsters
      tags:
      - Tipsters
      responses:
        '200':
          description: tipsters listed
          content: {}
    post:
      summary: Creates a Tipster
      tags:
      - Tipsters
      parameters: []
      responses:
        '201':
          description: tipster created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                user:
                  type: string
                  example: john_doe
              required:
              - name
              - user
  "/api/v1/tipsters/{id}":
    get:
      summary: Show a tipster
      tags:
      - Tipsters
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: show tipster
          content: {}
    put:
      summary: Updates a tipster
      tags:
      - Tipsters
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: tipster updated
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                user:
                  type: string
                  example: john_doe
    delete:
      summary: Show a tipster
      tags:
      - Tipsters
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '204':
          description: tipster deleted
          content: {}
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
